### ISSUE TITLE
Default KERNEL_MAX_SIZE is too low for MiniDexed

### ISSUE THREAD

**Issue by u77345** [probonopd/CircleNetboot#1]
The 2MB default max kernel size (KERNEL_MAX_SIZE) is less than a regular MiniDexed image size (2.5M) and the transfer fails with "Cannot Write". I suggest upping the default to 4MB for the published binary.

**Comment by probonopd** [comment]
Thanks @u77345. Isn't this what

https://github.com/probonopd/CircleNetboot/blob/ed9c83aec64466b4a95b3c19c1d7a76ad97b49b7/.github/workflows/build.yml#L23

is doing?

**Comment by u77345** [comment]
Fair, I did not look at the GitHub build. I built locally.
