### ISSUE TITLE
Add support for the RPI Zero / Zero 2W as they don't have ethernet

### ISSUE THREAD

**Issue by shawnpinciara** [probonopd/CircleNetboot#3]

**Comment by probonopd** [comment]
It is not possible to enable booting via Ethernet on devices that don't have Ethernet. One could theoretically use an USB Ethernet adapter, but I doubt anyone will put in the effort to make this happen.

In any case, I am not the author of this code. This repository just compiles https://github.com/rsta2/circle/tree/master/sample/38-bootloader, so any changes in that bootloader would need to be addressed at https://github.com/rsta2/circle/issues.
